apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVdXVkdEQURFSVdLWVE3NlU=
  AWS_SECRET_ACCESS_KEY: R1E4cU5jKzZCU1hLcUNPY0ZyT0lOemQ1YzJJVm1xY0w2OVlYOStRQQ==
