apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: weather-prediction-deployment
spec:
  name: weather-prediction
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: undercoverducky/weatherpredictionmodel:0.0.5-amd64
          name: weather-regression
          ports:
            - containerPort: 9000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
        terminationGracePeriodSeconds: 1
    graph:
      children: []
      endpoint:
        type: REST
      name: weather-regression
      type: MODEL
    labels:
      version: v1
    name: weather-regression-component
    replicas: 1